//index.js
//获取应用实例
const app = getApp()

Page({
  data: {
    members: [
      { id: "1", name: '苗景尧', gender: '男' },
      { id: "2", name: '李安澜', gender: '男' },
      { id: "3", name: '周倬旸', gender: '男' },
      { id: "4", name: '苏慕杭', gender: '男' },
      { id: "5", name: '田裕沛', gender: '男' },
      { id: "6", name: '李明澄', gender: '男' },
      { id: "7", name: '刘士彰', gender: '男' },
      { id: "8", name: '孟子祺', gender: '男' },
      { id: "9", name: '李永安', gender: '男' },
      { id: "10", name: '王梓杰', gender: '男' },
      { id: "11", name: '张瑀田', gender: '男' },
      { id: "12", name: '刘润镈', gender: '男' },
      { id: "13", name: '郑新宇', gender: '男' },
      { id: "14", name: '杨秉锟', gender: '男' },
      { id: "15", name: '邢书然', gender: '男' },
      { id: "16", name: '关柏森', gender: '男' },
      { id: "17", name: '吴桉锐', gender: '男' },
      { id: "18", name: '苗宸语', gender: '男' },
      { id: "19", name: '李鸣飞', gender: '男' },
      { id: "20", name: '石昌轩', gender: '男' },
      { id: "21", name: '张晋吉', gender: '男' },
      { id: "22", name: '刘涵宇', gender: '男' },
      { id: "23", name: '邹家塬', gender: '男' },
      { id: "24", name: '郝一帆', gender: '男' },
      { id: "25", name: '王禹森', gender: '男' },
      { id: "26", name: '陈若维', gender: '女' },
      { id: "27", name: '丁若曦', gender: '女' },
      { id: "28", name: '赵钰涵', gender: '女' },
      { id: "29", name: '崔素妍', gender: '女' },
      { id: "30", name: '金卓萱', gender: '女' },
      { id: "31", name: '崔严兮', gender: '女' },
      { id: "32", name: '裴若瑜', gender: '女' },
      { id: "33", name: '范思睿', gender: '女' },
      { id: "34", name: '田雨昕', gender: '女' },
      { id: "35", name: '王美懿', gender: '女' },
      { id: "36", name: '许馨戈', gender: '女' },
      { id: "37", name: '周钰', gender: '女' },
      { id: "38", name: '张雅琳', gender: '女' },
      { id: "39", name: '林小婷', gender: '女' },
      { id: "40", name: '梁若歆', gender: '女' },
      { id: "41", name: '齐洪霆锋', gender: '女' },
      { id: "42", name: '龚楚淇', gender: '女' },
      { id: "43", name: '董宇琦', gender: '女' },
      { id: "44", name: '王稀', gender: '女' },
      { id: "45", name: '常语格', gender: '女' },
      { id: "46", name: '李诺晴', gender: '女' },
      { id: "47", name: '马泽然', gender: '女' },
      { id: "48", name: '王依茹赛罕', gender: '女' }
    ]
  },
})
